#!/bin/bash

NGINX_VERSION=${NGINX_VERSION-1.15.8}
HEADERS_MORE_VERSION=${HEADERS_MORE_VERSION-0.33}
NPS_VERSION=${NGINX_PAGE_SPEED_VERSION-1.13.35.2}
PCRE_VERSION=${PCRE_VERSION-8.42}
ZLIB_VERSION=${ZLIB_VERSION-1.2.11}

nginx_tarball_url=http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
headers_more_nginx_module_url=https://github.com/openresty/headers-more-nginx-module/archive/v${HEADERS_MORE_VERSION}.tar.gz
nginx_page_speed_url=https://github.com/apache/incubator-pagespeed-ngx/archive/v${NPS_VERSION}-stable.tar.gz
psol_url=https://dl.google.com/dl/page-speed/psol/${NPS_VERSION}-x64.tar.gz
pcre_tarball_url=http://iweb.dl.sourceforge.net/project/pcre/pcre/${PCRE_VERSION}/pcre-${PCRE_VERSION}.tar.bz2
zlib_url=http://zlib.net/zlib-${ZLIB_VERSION}.tar.gz

set -e

temp_dir=$(mktemp -d /tmp/nginx.XXXXXXXXXX)

echo "Serving files from /tmp on $PORT"
cd /tmp
python -m SimpleHTTPServer $PORT &

cd $temp_dir
echo "Temp dir: $temp_dir"

echo "Downloading $nginx_tarball_url"
curl --silent -L $nginx_tarball_url | tar xzv

echo "Downloading $pcre_tarball_url"
(cd nginx-${NGINX_VERSION} && curl --silent -L $pcre_tarball_url | tar xvj )

echo "Downloading $headers_more_nginx_module_url"
(cd nginx-${NGINX_VERSION} && curl --silent -L $headers_more_nginx_module_url | tar xvz)

echo "Downloading $zlib_url"
(cd nginx-${NGINX_VERSION} && curl --silent -L $zlib_url | tar xvz )

echo "Downloading $nginx_page_speed_url"
(cd nginx-${NGINX_VERSION} && curl --silent -L $nginx_page_speed_url | tar xvz )

echo "Downloading $psol_url"
(cd nginx-${NGINX_VERSION}/incubator-pagespeed-ngx-${NPS_VERSION}-stable && curl --silent -L $psol_url | tar xvz)

echo "Installing uuid-dev"
apt-get update && apt-get install -y uuid-dev libperl-dev

(
  cd nginx-${NGINX_VERSION}
  ./configure \
    --with-pcre=pcre-${PCRE_VERSION} \
    --with-zlib=zlib-${ZLIB_VERSION} \
    --with-http_gzip_static_module \
    --with-http_realip_module \
    --with-http_ssl_module \
    --with-http_v2_module \
    --prefix=/tmp/nginx \
    --add-module=${temp_dir}/nginx-${NGINX_VERSION}/headers-more-nginx-module-${HEADERS_MORE_VERSION} \
    --add-module=${temp_dir}/nginx-${NGINX_VERSION}/incubator-pagespeed-ngx-${NPS_VERSION}-stable
  make
  make install
)

cp /tmp/nginx/sbin/nginx $1
